version: "3.8"
services:    
  qdrant:
    image: qdrant/qdrant
    ports:
      - 6333:6333
      - 6334:6334
    environment:
      - TZ=America/New_York
    volumes:
      - ./volumes/qdrant:/qdrant/storage
