# Note: env var substitution is supported via $FOO or ${FOO} syntax

# Turn on debug logging
DEBUG: false
# Control the Zillion logger's log level. DEBUG flag overrides this.
LOG_LEVEL: WARNING
# Chunk size for loading datasource query results at the combined layer
LOAD_TABLE_CHUNK_SIZE: 5000
# Connection string for Zillion metadata DB
ZILLION_DB_URL: sqlite:////tmp/zillion.db
# Where to store adhoc SQLite databases
ADHOC_DATASOURCE_DIRECTORY: /tmp
# Either "sequential" or "multithread"
DATASOURCE_QUERY_MODE: sequential
# Set a timeout in seconds for datasource layer queries
DATASOURCE_QUERY_TIMEOUT: null

# These vars can be used to substitute values in connection URLs by datasource.
DATASOURCE_CONTEXTS:
  test_datasource1:
    schema: testdb2
    somevar: other_val
  test_datasource2:
    user: totalhack
    pass: foo