# Note: env var substitution is supported via $FOO or ${FOO} syntax

# Turn on debug logging
DEBUG: false
# Control the Zillion logger's log level. DEBUG flag overrides this.
LOG_LEVEL: WARNING
# Chunk size for loading datasource query results at the combined layer
LOAD_TABLE_CHUNK_SIZE: 5000
# Connection string for Zillion metadata DB
DB_URL: sqlite:////tmp/zillion.db

# If NLP extras are installed:
# OPENAI_API_KEY: <key>
# OPENAI_MODEL: gpt-3.5-turbo
# QDRANT_HOST: localhost

# Where to store adhoc SQLite databases
ADHOC_DATASOURCE_DIRECTORY: /tmp
# Either "sequential" or "multithread"
DATASOURCE_QUERY_MODE: sequential
# Set a timeout in seconds for datasource layer queries
DATASOURCE_QUERY_TIMEOUT: null
# Max number of parallel query threads
DATASOURCE_QUERY_WORKERS: 4
# Limit the number of joins to consider in each possible combination of joins
# when searching for combinations that satisfy the report grain. This is
# necessary to prevent combinatorial explosion for larger schema with many
# ways to satisfy a report, typically coming into play for many-dimensional
# reports. This effectively limits the number of joins in a single query.
DATASOURCE_MAX_JOINS: null
# Once we reach N join combos that cover the grain we will stop searching
DATASOURCE_MAX_JOIN_CANDIDATES: 100

# These vars can be used to substitute values in connection URLs by datasource.
DATASOURCE_CONTEXTS:
  test_datasource1:
    schema: testdb2
    somevar: other_val
  test_datasource2:
    user: totalhack
    pass: foo